# Generated by Django 5.0.7 on 2024-08-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_clientmodel_client_rename_ordermodel_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='orders',
            field=models.ManyToManyField(null=True, to='backend.order'),
        ),
    ]
