# Generated by Django 5.0.7 on 2024-08-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_client_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='orders',
            field=models.ManyToManyField(blank=True, to='backend.order'),
        ),
    ]
