# Generated by Django 5.0.7 on 2024-08-12 21:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_client_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='route',
            name='origin',
        ),
        migrations.AlterField(
            model_name='route',
            name='estimated_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='line',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='route',
            name='total_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='total_products',
            field=models.IntegerField(null=True),
        ),
    ]
