# Generated by Django 5.0.7 on 2024-08-13 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_route_estimated_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.client'),
        ),
    ]
